server:
  port: 8766
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
spring:
  application:
    name: zuul-proxy
zuul:
  routes:
    api-user:
      path: /user/*
      serviceId: service-user
    api-order:
      path: /order/*
      serviceId: service-order